### ISSUE TITLE
awesome-egov-de

### ISSUE THREAD

**Issue by codedust** [bundestag/awesome-germany#2]
Hi! I maintain an awesome list that is very similar to yours (https://github.com/codedust/awesome-egov-de/). Would you be interessted in merging our efforts?

**Comment by darkdragon-001** [comment]
Yes sure, this sounds like a great idea!

I would propose to use the _bundestag_ organization as this allows to add multiple maintainers.

What do you suggest to merge the actual contents? I think it is important to stick to the [awesome manifesto](https://github.com/sindresorhus/awesome/blob/main/awesome.md) instead of aiming for a complete list (this might also include removing some of the links I added as I didn't really have a reviewer for the awesomness of the contents).

**Comment by codedust** [comment]
👍 for using the bundestag organization!

Considering awesomeness: I'm thinking about where to draw the line here. E.g., the [policies section](https://github.com/codedust/awesome-egov-de#policies) in awesome-egov-de is super helpful, tough I wouldn't consider all policies *awesome* in that sence. There probably is a difference between *things you should know when working in in/with government* (which is what I focused on so far) and *things that are truely awesome in the german government domain* (which seems to be your focus).

Maybe, `awesome-egov-de` could focus on learning resources and where to find things (like documentation, podcasts, policies, code repositories, etc.) while `awesome-germany` focusses on concrete projects and tools?

What do you think?

**Comment by darkdragon-001** [comment]
I agree that both repositories have a different user focus (this repository focuses on citizens while awesome-eogov-de focuses on people working in/with administration) and as such it doesn't make sense to merge them.
